### PR TITLE
Make global transaction available

### PR DESCRIPTION
**Pull request by aperisic**
Make global transaction available for much faster insert of a large number of items

### CODE REVIEW

**Comment by mqudsi** [comment]
Hi @aperisic thanks for working on this!

I tend to prefer lambdas that begin and commit the transaction automatically for safety reasons, rather than expecting the user to always remember to call commit. 

Would that still work for you?

**Comment by aperisic** [comment]
I am not sure if lambda is the best choice. Maybe having one IDisposable
object that would open and close the transaction.
It seems to me more to the point. Like:

using( var session = new SqliteCacheSession(cache))
{
}

that way transaction could go around and be disposed outside the scope
where it is created.

session = new SqliteCacheSession(cache)
....
session.Dispose()

I added the change.

Aleksandar

**Comment by mqudsi** [comment]
That works, but I'm not sure I see I agree with the ergonomics of having it be a top-level object you'd need to use DI to get an instance of, as the object itself can't be used directly (e.g. you'd always have to inject it alongside a full SqliteCache/IDistributedCache instance). As using it requires a concrete type or at least our own interface, why not just add a BeginTransaction() or CreateTransaction() routine returning the IDisposable to the SqliteCache instance? That'll simply reasoning about the DI.

**Comment by aperisic** [comment]
Not sure, really...
This is just a wrapper...

This is the best I can do. You can create Session on your own, you can
use it in DI, so everything is covered. 1. using, 2. DI, 3. new, all
covered and we do not create a new cache object just make a small
wrapper around an existing one which was the intention.

Anyway, it works much faster if session is created. I will remove the
branch soon enough. Do not know what to do about it more.

Regards,
Aleksandar

**Comment by mqudsi** [comment]
Version 5.0 of this library uses a separate connection per call (out of a connection pool) in order to avoid threading issues in non-web contexts. This makes it almost impossible to persist a transaction, so I'm going to have to close this.

Note that the 5.0 release contains numerous other improvements to performance. The usage of WAL mode should be an invisible fix for pretty much all performance issues and we've also merged support for a bulk insert feature that can be used to further speed things up.

**Pull request closed without merging**
